api_1_0/__init__.py
from flask import Blueprint, redirect
from flask_restplus import Api

api1 = Blueprint('api', __name__, url_prefix='/api/1')
api = Api(api1)

from api_1_0.endpoints.post import nsPost
from api_1_0.endpoints.user import nsUser
from api_1_0.endpoints.task import nsTask
from api_1_0.endpoints.getfilecontent import nsFile

api.add_namespace(nsPost)
api.add_namespace(nsUser)
api.add_namespace(nsTask)
api.add_namespace(nsFile)

@api1.route('/')
def index():
    return (api.render_doc())

app/pages/__init__.py
from flask import Blueprint

pages = Blueprint('pages', __name__)

from . import routes

app/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/sb-admin.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('pages.index') }}">Bioinf toolbox</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                {% if (current_user.is_authenticated) %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ current_user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ url_for('pages.user', username=current_user.username) }}"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            {% if current_user == user %}<a href="{{ url_for('pages.profile') }}"><i class="fa fa-fw fa-gear"></i> Settings</a>{% endif %}
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ url_for('auth.logout') }}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                  {% if not (current_user.is_authenticated) %}
                    <li>
                        <a href="{{ url_for('auth.login') }}"><i class="fa fa-fw fa-home"></i> Login</a>
                    </li>
                  {% endif %}
                    {% if (current_user.is_authenticated) %}

                    <li>
                      <a href="{{ url_for('pages.index') }}"><i class="fa fa-fw fa-home"></i>Home</a>
                    </li>
                    <li>
                      <a href="{{ url_for('pages.new_post') }}"><i class="fa fa-fw fa-comment-o"></i>New Post</a>
                    </li>
                    <li>
                      <a href="{{ url_for('tools.upload') }}"><i class="fa fa-fw fa-upload"></i>Upload file</a>
                    </li>
                    <li>
                      <a href="{{ url_for('pages.list_files') }}"><i class="fa fa-fw fa-folder"></i>List Files</a>
                    <li>
                    <li>
                      <a href="{{ url_for('api.index') }}">API</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Tools <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="{{ url_for('tools.blast') }}">BLAST</a>
                            </li>
                            <li>
                                <a href="{{ url_for('tools.caw') }}">Cancer Analysis Workflow</a>
                            </li>
                            <li>
                                <a href="{{ url_for('tools.fib_task') }}">Fibonacci</a>
                            </li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>

            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">
            {% block content %}
            <div class="container-fluid">
              {% for message in get_flashed_messages() %}
                <!-- Page Heading -->
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Bioinf toolbox
                        </h1>

                    </div>
                </div>
                {% endfor %}
                <!-- /.row -->
                {% block page_content %}{% endblock %}
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    {% endblock %}

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

</body>


</html>
{{ moment.include_moment() }}